export const backgroundImageMapping : Record<string, string> = {
    '01d': 'clear-day.jpg',
    '01n': 'clear-night.jpg',
    '02d': 'cloudy-day.jpg',
    '02n': 'cloudy-night.jpg',
    '03d': 'cloudy-day.jpg',
    '03n': 'cloudy-night.jpg',
    '04d': 'cloudy-day.jpg',
    '04n': 'cloudy-night.jpg',
    '09d': 'rainy-day.jpg',
    '09n': 'rainy-night.jpg',
    '10d': 'rainy-day.jpg',
    '10n': 'rainy-night.jpg',
    '11d': 'thunderstorm-day.jpg',
    '11n': 'isolated-thunderstorms-night.jpg',
    '13d': 'snowy-day.jpg',
    '13n': 'snowy-night.jpg',
    '50d': 'cloudy-day.jpg',
    '50n': 'cloudy-night.jpg',
};
